### ISSUE TITLE
Menu bar text is hard to read in light green. How to change to black?

### ISSUE THREAD

**Issue by lenn5** [fataio/cpumeter#12]
I just installed the latest version of cpuinfo 1.4 on my iMac running High Sierra. The menu bar text is now a light green color that is very hard to read when using a white menu bar. How can I change the cpuinfo menu text back to black?

thx

**Comment by yusukeshib** [comment]
@lenn5 I see, I agree. I will be changing today.

**Comment by yusukeshib** [comment]
@lenn5 New app version deployed.
