### ISSUE TITLE
menu bar text still green on Mac running El Capitan. 

### ISSUE THREAD

**Issue by lenn5** [fataio/cpumeter#14]
On my older MBP running El Capitan the CPU usage text is still light green and hard to read. Am using v1.4.1. Although on my iMac running High Sierra the text is black running the same version of cpuinfo. How do I change the text color to black? 
thx

**Comment by yusukeshib** [comment]
@lenn5  Thanks for reporting, it's fixed and merged.
Please wait for v1.4.2 release from App store ( or you can try from brew ).
