### ISSUE TITLE
Action of menu item 'コアを個別に表示' is not connected with Cpuinfo delegate

### ISSUE THREAD

**Issue by yozjp** [fataio/cpumeter#15]
The menu item 'コアを個別に表示' in MainMenu.xib for Japanese localization is not connected with the method 'updateCoresIndividuality:' in CpuinfoDelegate.mm.
So, the feature does not work in Japanese desktop.
Anyway, thank you for your work :)

**Comment by yusukeshib** [comment]
@yozjp Thanks for reporting, it's fixed and merged.
Please wait for v1.4.2 release from App store ( or you can try from brew ).
