### ISSUE TITLE
Typo on `individually`

### ISSUE THREAD

**Issue by 17twenty** [fataio/cpumeter#21]
https://github.com/yusukeshibata/cpuinfo/blob/73b1b508c85f5f8c55e6da9d1fb658992d44a18e/res/en.lproj/MainMenu.xib#L97

Happy to put a PR up but wanted to make sure it was a typo and not a deliberate thing?

**Comment by yusukeshib** [comment]
@17twenty Thanks for mentioning this, It's fixed on 1.4.3.
