### ISSUE TITLE
Great app, just the bar/icon is too wide

### ISSUE THREAD

**Issue by m-cerveny** [fataio/cpumeter#29]
Would it be possible to make the bar graphics make about 2/3 of its current width? It would fit much netter the aesthetics.

Maybe a narrow version could be added too, that would not take too much space when showing individual cores.

**Comment by m-cerveny** [comment]
Now I see that the "show individual cores" actually uses very nice not-so-wide version of the bar. Include an option to use the small (individual core) version. That would be fantastic!!

**Comment by yusukeshib** [comment]
I adjusted the width a little (32px -> 28px) in the release yesterday.
