### ISSUE TITLE
B/W theme seems off in dark theme macOS 11

### ISSUE THREAD

**Issue by m-cerveny** [fataio/cpumeter#32]
![image](https://user-images.githubusercontent.com/11475311/112305683-47f72500-8c9f-11eb-8dc9-75c5c943fca9.png)
When B/W theme selected, it seem bit off. See screenshot. I appears inverse when dark theme (light writing) is displayed.

**Comment by yusukeshib** [comment]
Fixed by the new release yesterday! check it please.
