### ISSUE TITLE
CPU percentage display number font size consistency

### ISSUE THREAD

**Issue by LeMerlot** [fataio/cpumeter#35]
Absolutely love it! cpuinfo replaced all my CPU-hogging CPU meters like iStatMenus for me. 

Only change I would love: **CPU percentage display number font size same like Mac's date/hour view font size for consistency and better readability** – in the recent version it is too small (change easy to implement).

**Comment by yusukeshib** [comment]
Thanks, I agree, I will updating it.

**Comment by yusukeshib** [comment]
fixed on 1.4.9
