### ISSUE TITLE
Please bring back the borderless design. 

### ISSUE THREAD

**Issue by m-cerveny** [fataio/cpumeter#38]
The old design was very "modern" and smooth. Bring it back please, maybe as an option? 

Or maybe make it identical (the edges) to the macOS Monterey battery icon. That would be greatly consistent! 

Thank you!

**Comment by yusukeshib** [comment]
Hi @m-cerveny 
I agree, the version I released yesterday wasn't good enougth for me too :)
I just submitted a new version to AppStore.
How about it?

<img width="640" alt="1" src="https://user-images.githubusercontent.com/127269/156466203-18dc457c-a118-4ff0-841f-9e8ddfa09ac6.png">
<img width="640" alt="5" src="https://user-images.githubusercontent.com/127269/156466186-c54121e5-c563-4a77-bfa1-abd4957d9284.png">
<img width="640" alt="3" src="https://user-images.githubusercontent.com/127269/156466190-ecffbff8-b283-4a62-87d7-88ed822e998d.png">

**Comment by yusukeshib** [comment]
I will add previous design as another theme in the next release.

**Comment by yusukeshib** [comment]
I submitted 1.5.0, and brought back the previous design as "Borderless" theme.
