### ISSUE TITLE
on my M1 mac mini, only 1 core shows activity

### ISSUE THREAD

**Issue by luckman212** [fataio/cpumeter#41]
I compiled a new build based on 1.4.9 code

I like the new design but, only core #0 shows any activity, even when I am loading all cores.... 

see image below, showing cpuinfo next to [Stats](https://github.com/exelban/stats)... 

![image](https://user-images.githubusercontent.com/1992842/156470586-331b4e2b-a68a-4616-a787-e00e0e5f076f.png)

**Comment by yusukeshib** [comment]
Hi @luckman212 
Thank you for finding it, I fixed it, and submitted version 1.5.0 just now with the fix.

**Comment by luckman212** [comment]
It works great, thank you!

![image](https://user-images.githubusercontent.com/1992842/156615946-54e81fc0-d695-49e2-a826-1f9852f3f311.png)
