### ISSUE TITLE
Borderless theme has a icon size bug with individual cores

### ISSUE THREAD

**Issue by m-cerveny** [fataio/cpumeter#44]
It seems you have the wrong value (still the old one?) defined as width for borderless theme. See image.
<img width="162" alt="image" src="https://user-images.githubusercontent.com/11475311/156649778-140103e9-49c1-4104-8d1e-990c1c47c42e.png">

Btw, I love the default/bw individual cores implementation. Really easy on the eye...
<img width="159" alt="image" src="https://user-images.githubusercontent.com/11475311/156650094-869ac4f5-4043-4d53-9a7d-fdf9c7a7c2ff.png">

**Comment by yusukeshib** [comment]
Thank you! 
It looks there's an unstable behavior for updating total width of the app, will be fixing in the next release.
