### ISSUE TITLE
`brew cask install cpuinfo` fails with latest release

### ISSUE THREAD

**Issue by claui** [fataio/cpumeter#6]
Since the [latest update](https://github.com/yusukeshibata/cpuinfo/tree/025ead013e0a3ba2b85974a9d3cef1f2b3a710f7/dist) of `dist/cpuinfo.zip`, the app fails to install on Homebrew-cask because the app bundle seems to be missing from the root folder of the archive:

```
± brew cask install cpuinfo
==> Downloading https://github.com/yusukeshibata/cpuinfo/blob/master/dist/cpuinfo.zip?raw=true
######################################################################## 100,0%
==> No checksum defined for Cask cpuinfo, skipping verification
Error: It seems the App source is not there: '/usr/local/Caskroom/cpuinfo/latest/cpuinfo.app'
Error: An error occured during installation of Cask cpuinfo: It seems the App source is not there: '/usr/local/Caskroom/cpuinfo/latest/cpuinfo.app'
Error: nothing to install
```

There seems to be a folder hierarchy inside `dist/cpuinfo.zip`, apparently by mistake. Besides, the archive contains two app bundles instead of one.

In order to fix `brew cask install cpuinfo`, would you mind uploading a new version of the archive with the folder hierarchy removed?

Thanks in advance and greetings from Caskroom!

**Comment by yusukeshib** [comment]
Thanks!
Fixed zip file structure.

**Comment by claui** [comment]
Thanks Yusuke! Works like a charm now :)
