### ISSUE TITLE
No show

### ISSUE THREAD

**Issue by kul1** [fataio/cpumeter#8]
![screen shot 2018-04-17 at 10 30 12 am](https://user-images.githubusercontent.com/3953832/38880030-572120c0-422a-11e8-8c5b-a383f73d8f8f.png)

After ran install with 
brew cask install cpuinfo
and reboot
Nothing shown in menu yet.

**Comment by gingerbeardman** [comment]
@kul1 that command installs the app to `/Applications/cpuinfo.app`

but then you need to run the app manually
